name: .NET

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore USerializer
    - name: Build
      run: dotnet build USerializer --no-restore --configuration Release
    - name: Test
      run: dotnet test USerializer --no-build --verbosity normal    
  Benchmark:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: DotnetPublish
      run: dotnet publish PerformanceTests --configuration Release -o Release
    - name: RunPerformanceTests
      run: dotnet ./Release/PerformanceTests.dll --commit $(git rev-parse --short "$GITHUB_SHA")
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    
