name: UnityRepo

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ master ]
    
jobs:
  TestAndBuild:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test USerializer --verbosity normal
    - name: Publish
      run: dotnet publish USerializer --configuration Release -o PublishDirectory
    - uses: actions/upload-artifact@v2
      with:
        name: UserializerPublished
        path: PublishDirectory
  CopyToUnityRepo:
    needs: TestAndBuild
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: UserializerPublished
        path: PublishDirectory
    - name: Push to USerializerUnity
      uses: darkquasar/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
          source-directory: 'PublishDirectory'
          destination-github-username: 'ddalacu'
          destination-repository-name: 'USerializerUnity'
          user-email: ddalacu@yahoo.com
          target-branch: master
          target-directory: 'Plugins'
    - name: Pushes to another repository
      uses: geekyeggo/delete-artifact@v1
      with:
        name: UserializerPublished